### ISSUE TITLE
Crashes on launch (Class casting issue)

### ISSUE THREAD

**Issue by dfreemanRIIS** [dfreemanRIIS/ShoppingCart#1]
@RIISBMarshall

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.dfreeman.shoppingcart, PID: 2527
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.dfreeman.shoppingcart/com.example.dfreeman.shoppingcart.FirstScreen}: java.lang.ClassCastException: android.app.Application cannot be cast to com.example.dfreeman.shoppingcart.Controller
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.example.dfreeman.shoppingcart.Controller
                      at com.example.dfreeman.shoppingcart.FirstScreen.onCreate(FirstScreen.java:26)
                      at android.app.Activity.performCreate(Activity.java:6237)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by dfreemanRIIS** [comment]
Fixed in commit: 2ebcc05fb6382623844c4603ab0e8aa22cb63675
